package generator;

import java.util.ArrayList;

public class Ingredients {

	public static String[] veggies = {
		"artichoke",
		"arugula",
		"asparagus",
		"avocado",
		"bamboo",
		"beet",
		"bell pepper",
		"bok choy",
		"broccoli",
		"brussels sprouts",
		"cabbage",
		"capers",
		"carrot",
		"cauliflower",
		"celery",
		"cherry tomato",
		"chilies",
		"collard",
		"corn",
		"cucumber",
		"daikon",
		"eggplant",
		"endive",
		"fennel",
		"garlic",
		"ginger",
		"green beans",
		"horseradish",
		"jalapeno",
		"kale",
		"kimchi",
		"kohlrabi",
		"leek",
		"lettuce",
		"mixed vegetables",
		"mushroom",
		"mustard greens",
		"nori",
		"okra",
		"onion",
		"parsley",
		"parsnip",
		"peas",
		"poblano",
		"potato",
		"pumpkin",
		"radicchio",
		"radish",		
		"rutabaga",
		"sauerkraut",
		"scallion",
		"seaweed",
		"serrano",
		"shallot",
		"spinach",
		"squash",
		"swiss chard",
		"tomatillo",
		"tomato",
		"turnip",
		"vegetable stock",
		"zucchini"
	};
	
	public static String[] dairy = {
		"american cheese",
		"asiago",
		"blue cheese",
		"brie",
		"butter",
		"camembert",
		"cheddar",
		"cottage cheese",
		"cream cheese",
		"cream",
		"custard",
		"edam",
		"feta",
		"goat cheese",
		"gouda",
		"gruyere",
		"half-and-half",
		"ice cream",
		"margarine",
		"mascarpone",
		"milk",
		"monterey jack",
		"mozzarella",
		"parmesan",
		"pepper jack",
		"provolone",
		"raclette",
		"ricotta",
		"romano",
		"sour cream",
		"stilton",
		"swiss cheese",
		"velveeta",
		"yogurt"
	};
	
	public static String[] grains = {
		"bagel",
		"baguette",
		"baking powder",
		"baking soda",
		"barley",
		"bean sprouts",
		"biscuit",
		"bread crumbs",
		"bread",
		"buns",
		"ciabatta",
		"cornbread",
		"cornmeal",
		"cornstarch",
		"couscous",
		"crackers",
		"cream of tartar",
		"cream of wheat",
		"croissant",
		"croutons",
		"dough",
		"english muffin",
		"flour",
		"lasagne",
		"macaroni",
		"noodles",
		"oats",
		"orzo",
		"pancake mix",
		"pasta",
		"pie crust",
		"pierogi",
		"pita",
		"pizza crust",
		"pizza dough",
		"popcorn",
		"quinoa",
		"ravioli",
		"rice",
		"rolls",
		"rye bread",
		"spaghetti",
		"sourdough",
		"tortilla",
		"tortellini",
		"vermicelli",
	};
	
	public static String[] meats = {
		"bacon",
		"beef bone",
		"beef roast",
		"beef stock",
		"beef",
		"brisket",
		"canadian bacon",
		"chicken bone",
		"chicken stock",
		"chicken wings",
		"chicken",
		"chorizo",
		"corned beef",
		"duck",
		"giblets",
		"goose",
		"ground beef",
		 "ham",
		"hot dog",
		 "lamb",
		"liver",
		"oxtail",
		"pancetta",
		"pastrami",
		"pepperoni",
		"polish sausage",
		"pork belly",
		"pork chop",
		"pork",
		"prosciutto",
		"ribs",
		"salami",
		 "sausage",
		"sirloin",
		"spam",
		"steak",
		"turkey"
};
	
	

public static String[] seafood = {
	"anchovies",
	"bass",
	"calamari",
	"catfish",
	"cod",
	"crab",
	"cuttlefish",
	"eel",
	"fish stock",
	"flounder",
	"halibut",
	"herring",
	"lobster",
	"mackerel",
	"marlin",
	"mussel",
	"oyster",
	"oyster",
	"salmon",
	"sardines",
	"scallop",
	"shrimp",
	"swordfish",
	"tilapia",
	"trout",
	"tuna"
};

public static String[] legumes = {
	"black bean",
	"cannellini beans",
	"chickpea",
	"chili beans",
	"edamame",
	"fava beans",
	"hummus",
	"kidney beans",
	"lentil",
	"navy beans",
	"pinto",
	"red beans",
	"refried beans",
	"soybeans",
	"tofu",
	"great northern beans"
};
	
	public static String[] fruits = {
		"apple",
		"apricot",
		"banana",
		"blackberries",
		"blueberries",
		"cherries",
		"coconut",
		"cranberries",
		"date",
		"fig",
		"grape",
		"grapefruit",
		"guava",
		"kiwi",
		"kumquat",
		"lemon",
		"lime",
		"mango",
		"orange",
		"papaya",
		"peach",
		"pear",
		"pineapple",
		"plum",
		"prune",
		"raisin",
		"raspberries",
		"rhubarb",
		"strawberries",
		"watermelon",
	};
	
	public static String[] spices = {
		"allspice",
		"basil",
		"bay leaves",
		"beef bouillon",
		"caraway",
		"cardamom",
		"cayenne",
		"celery salt",
		"celery seed",
		"chili powder",
		"chipotle",
		"chive",
		"cilantro",
		"cinnamon",
		"clove",
		"coriander",
		"cumin",
		"curry powder",
		"dill",
		"garlic powder",
		"italian seasoning",
		"mustard powder",
		"nutmeg",
		"old bay",
		"onion powder",
		"oregano",
		"paprika",
		"pepper",
		"red pepper flakes",
		"rosemary",
		"saffron",
		"sage",
		"salt",
		"star anise",
		"taco seasoning",
		"tarragon",
		"thyme",
		"turmeric",
		"vanilla",
		"wasabi",
	};
	
	public static String[] alcohol = {
		"beer",
		"brandy",
		"champagne",
		"cooking wine",
		"gin",
		"irish cream",
		"kahlua",
		"port",
		"prosecco",
		"red wine",
		"rum",
		"sherry",
		"tequila",
		"triple sec",
		"vermouth",
		"vodka",
		"whiskey",
		"white wine",
	};
	
	public static String[] condiments = {
		"apple cider vinegar",
		"balsamic vinegar",
		"barbecue sauce",
		"blue cheese dressing",
		"buffalo sauce",
		"chili garlic sauce",
		"cocktail sauce",
		"dijon mustard",
		"fish sauce",
		"french dressing",
		"hoisin",
		"honey mustard",
		"hot sauce",
		"ketchup",
		"mayo",
		"mustard",
		"pesto",
		"ponzu",
		"ranch",
		"salsa",
		"soy sauce",
		"spaghetti sauce",
		"sriracha",
		"steak sauce",
		"tabasco sauce",
		"taco sauce",
		"tartar sauce",
		"thousand island",
		"vinegar",
		"white rice vinegar",
		"white vinegar",
		"wine vinegar",
		"worcestershire",
	};
	
	public static String[] other = {
		"almonds",
		"brown gravy",
		"caramel",
		"chocolate",
		"cocoa",
		"coffee",
		"cooking spray",
		"dill pickles",
		"egg",
		"french fries",
		"hazelnut",
		"honey",
		"mint",
		"miso",
		"oil",
		"olives",
		"olive oil",
		"peanuts",
		"pecans",
		"pistachios",
		"pizza sauce",
		"powdered sugar",
		"soup stock",
		"sugar",
		"sweet pickles",
		"syrup",
		"tomato paste",
		"tomato sauce",
		"vegetable oil",
		"walnuts",
		"white gravy",
		"yeast",
	};
	
	public static String[][] ingredientTypes = {
			veggies,
			dairy,
			grains,
			meats,
			seafood,
			legumes,
			fruits,
			spices,
			alcohol,
			condiments,
			other
	};
	
	public static String[] ingredientTypeNames = {
		"veggies",
		"dairy",
		"grains",
		"meats",
		"seafood",
		"legumes",
		"fruits",
		"spices",
		"alcohol",
		"condiments",
		"other"
	};
	
	public static ArrayList<String> getIngredientArray() {
		ArrayList<String> ingredientArray = new ArrayList<String>();
		
		for (String[] type : ingredientTypes) {
			for (String ingredient : type) {
				ingredientArray.add(ingredient);
			}
		}		
		return ingredientArray;
	}
}